### ISSUE TITLE
Missing paper and datasets query. 

### ISSUE THREAD

**Issue by psmail147** [Boeing/sdr-depressurization#1]
Hi there, 

In the README file it states "Please cite our paper below if you utilize these data sets". As far as I can see, there is no paper, please can you confirm it is meant to be this one: https://ieeexplore.ieee.org/document/10194079

Also, where are the benchmark datasets? The repository contains the README file and the LICENCE file, but nothing else. I would like to make use of the dataset for a university project. 

Many thanks, 

Phil.

**Comment by ethanenguyen** [comment]
Hi Phil,  
Thank you for reaching out.  Yes, that's the right paper.  We will work to add that to the README file.   

The benchmark datasets are in https://github.com/Boeing/sdr-hazards-classification/tree/main/src/sdr_hazards_classification/data.  That's our official repo that covers all types of hazards including depressurization.

Please let us know if you have more questions.

**Comment by ethanenguyen** [comment]
Closed
